apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xs3.aws.starter.org
  labels:
    plan: full
    provider: aws
spec:
  writeConnectionSecretsToNamespace: upbound-system
  compositeTypeRef:
    apiVersion: aws.starter.org/v1alpha1
    kind: XS3
  resources:
    - name: bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        spec: 
          forProvider:
            forceDestroy: true
            region: eu-north-1
      patches:
        - fromFieldPath: metadata.labels
          toFieldPath: metadata.labels
        - fromFieldPath: metadata.annotations
          toFieldPath: metadata.annotations
        - fromFieldPath: spec.providerConfigRef.name
          toFieldPath: spec.providerConfigRef.name
