apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: buckets.s3.aws.k8s.starter.org
  labels:
    crossplane.io/xrd: xbuckets.s3.aws.k8s.starter.org
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: s3.aws.k8s.starter.org/v1alpha1
    kind: XBucket
  patchSets:
    - name: deletionPolicyPatches
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.deletionPolicy
          toFieldPath: spec.deletionPolicy
    - name: providerPatches
      patches:
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.providerConfigRef
          toFieldPath: spec.providerConfigRef.name
  resources:
    - name: Bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
      patches:
        - type: PatchSet
          patchSetName: providerPatches
        - type: PatchSet
          patchSetName: deletionPolicyPatches
        - type: FromCompositeFieldPath
          fromFieldPath: spec.parameters.region
          toFieldPath: spec.forProvider.region
