apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.s3.aws.ucp.volvocars.biz
spec:
  group: s3.aws.ucp.volvocars.biz
  names:
    kind: XBucket
    plural: xbuckets
  claimNames:
    kind: Bucket
    plural: buckets
  defaultCompositionRef:
    name: buckets.s3.aws.ucp.volvocars.biz
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    region:
                      type: string
                      description: Geographic location of this S3 bucket.
                    providerConfigRef:
                      type: string
                      description: Crossplane provider credentials to use.
                      default: default
                    deletionPolicy:
                      type: string
                      default: Delete
                      description: DeletionPolicy specifies what will happen to the underlying external when this managed resource is deleted - either "Delete" or "Orphan" the external resource.
              required:
                - parameters
